version: '3.7'

services:

  web:
    build:
      context: .
      dockerfile: docker/prod/web/Dockerfile
    labels:
      - SERVICE_NAME=app
    environment:
    # used for proxy https://github.com/jwilder/nginx-proxy
      - VIRTUAL_HOST=${VUE_APP_HOST}
    expose:
      - 80
